### ISSUE TITLE
Formatting into an existing buffer?

### ISSUE THREAD

**Issue by Jayshua** [pyfisch/httpdate#12]
Would you accept a pull request exposing a format function that takes an &mut [u8; 29] to format into? I think this can be implemented by moving the Display::fmt implementation to its own pub function, since it already formats into a [u8; 29].

This is useful when avoiding allocations (or using an arena/bump allocator) and sending the response as an &[IoSlice] with the vectored writing functions.

**Comment by pyfisch** [comment]
I see why this is useful in some circumstances but I do not want to expand the public interface of the crate. I suggest you benchmark if the extra allocation is significant and if needed fork the crate.

**Comment by Jayshua** [comment]
It's more about the API ergonomics than the performance, the performance is fine I'm sure.

For anyone coming along later I did make [a fork](https://crates.io/crates/date_header) with this change and the changes suggested in #10 and #11 among other things.

Not being about the performance aside, if you wanted to take a look at my fork @pyfisch I was surprised to find that criterion reported somewhere between 60-70% performance improvement on the *parsing benchmarks* (not the encoding benchmark where the allocation was) on my computer. Not really sure why, since I wasn't intentionally doing any optimization. Maybe I just don't know how to use criterion? :shrug:

Also, maybe it's just me not understanding criterion again, but it looks to me like your [encoding benchmark](https://github.com/pyfisch/httpdate/blob/63f723c6eae30ec130a6c5625ec38c4b49b0891c/benches/benchmarks.rs#L45) is testing writing a static string rather than the HttpDate Display implementation?
