### ISSUE TITLE
Parsing non-GMT timezones fails

### ISSUE THREAD

**Issue by chesedo** [pyfisch/httpdate#16]
The following fails to parse. However, if understand RFC 822 correctly then this should be valid. While RFC 2616 which replaced 822 states only only numeric timezones should be valid and not named ones.

```rust
    assert!(parse_http_date("Sun, 02 Oct 2016 14:44:11 +0200").is_ok());
```

**Comment by pyfisch** [comment]
RFC 2616 is *very* obsolete, the current [RFC 9110](https://datatracker.ietf.org/doc/html/rfc9110#http.date) makes no reference to non-GMT timezones and defines the grammar.

Are you having issues with an implementation that does not emit GMT timestamps?
